#! /bin/bash

# Check if parameter is set
if [ -z "$1" ]; then
	echo "Missing parameter; Proper usage: 'stop-and-remove-dockercontainer <docker container name>'"
fi

CONTAINERNAME="$1

if [ $(docker inspect -f '{{.State.Running}}' $CONTAINERNAME) = "true" ]; then
	docker stop $CONTAINERNAME
fi

if [ "$(docker ps -q -f name=$CONTAINERNAME -f status=exited)" ]; then
	docker rm $CONTAINERNAME
fi
