#! /bin/bash

# Check if parameter is set
if [ -z "$1" ]; then
	echo "Missing parameter; Proper usage: 'stop-and-remove-dockercontainer <docker container name>'"
	exit 1
fi

CONTAINERNAME=$1

# Check if the container exists
if [ "$(docker ps -a -q -f name=$CONTAINERNAME)" ]; then
	echo "Container $CONTAINERNAME exists"
	# Check if container is running
	if [ "$(docker ps -q -f name=$CONTAINERNAME -f status=running)" ]; then
		echo "Container $CONTAINERNAME is running. Stopping it now..."
		docker stop $CONTAINERNAME
	else
		echo "Container $CONTAINERNAME is not running"
	fi
	echo "Removing container $CONTAINERNAME..."
	docker rm $CONTAINERNAME
else
	echo "Container $CONTAINERNAME does not exist"
fi

exit 0
