FROM maven-jdk8u181

ARG git_link
ARG java_app_runpath=/root/app/

RUN mkdir -p ${java_app_runpath}

RUN git clone ${git_link} ${java_app_runpath}

RUN mvn -f ${java_app_runpath}pom.xml clean package

EXPOSE 2222

CMD mvn -f /root/app/pom.xml exec:java -Dexec.mainClass="rest.RESTEmbeddedJetty" -s "/usr/share/maven/ref/settings-docker.xml"
